export const TOGGLE_LOADER = 'TOGGLE_LOADER';
export const SET_RESIDENT_LIST = 'SET_RESIDENT_LIST';
export const SET_RESIDENT_FILTER = 'SET_RESIDENT_FILTER';
export const SET_RESIDENT_SCHEDULE = 'SET_RESIDENT_SCHEDULE';
export const SET_RESIDENT_DATA = 'SET_RESIDENT_DATA';
export const TOGGLE_FILTER_LOADER = 'TOGGLE_FILTER_LOADER';
export const SET_TOOLTIP_VISIBILITY = 'SET_TOOLTIP_VISIBILITY';
export const SET_TOOLTIP_DATA = 'SET_TOOLTIP_DATA';
export const SET_VISIBILITY_OPEN_STATUS = 'SET_VISIBILITY_OPEN_STATUS';
export const SET_PROGRAM_INFO = 'SET_PROGRAM_INFO';
export const SET_ACTIVE_DASHBOARD = 'SET_ACTIVE_DASHBOARD';
export const SET_RO_TOOLTIP_VISIBILITY = 'SET_RO_TOOLTIP_VISIBILITY';
export const SET_RO_TOOLTIP_DATA = 'SET_RO_TOOLTIP_DATA';
export const SET_EXPIRED_DATA = 'SET_EXPIRED_DATA';

// Faculty Dashboard
export const SET_FACULTY_FILTER = 'SET_FACULTY_FILTER';
export const SET_FACULTY_LIST = 'SET_FACULTY_LIST';
export const SET_FACULTY_GROUP_LIST = 'SET_FACULTY_GROUP_LIST';
export const SET_FACULTY_DEPARTMENT_LIST = 'SET_FACULTY_DEPARTMENT_LIST';
export const SET_FACULTY_LOADER_STATE = 'SET_FACULTY_LOADER_STATE';
export const SET_FACULTY_COURSE = 'SET_FACULTY_COURSE';
export const SET_FACULTY_ACADEMIC_YEAR = 'SET_FACULTY_ACADEMIC_YEAR';
export const SET_FACULTY_RESIDENT_RECORDS = 'SET_FACULTY_RESIDENT_RECORDS';

// Program Evaluation Dashboard
export const SET_PROGRAM_EVAL_FILTER = 'SET_PROGRAM_EVAL_FILTER';
export const SET_PROGRAM_EVAL_ACADEMIC_YEARS = 'SET_PROGRAM_EVAL_ACADEMIC_YEARS';
export const SET_PROGRAM_EVAL_LOADER_STATE = 'SET_PROGRAM_EVAL_LOADER_STATE';
export const SET_PROGRAM_EVAL_RESIDENT_RECORDS = 'SET_PROGRAM_EVAL_RESIDENT_RECORDS';
